namespace:
  name: ''
  create: false
  enabled: false

deployment:
  name: ''
  enabled: false
  namespace: ''
  replicaCount: 1
  restartPolicy: Always
  args: { }
  image:
    repository: ''
    tag: ''
    pullPolicy: Always
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP

service:
  name: ''
  enabled: false
  type: ClusterIP
  namespace: flow
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP

resources:
  enabled: true
  limits:
    cpu: ''
    memory: ''
  requests:
    cpu: ''
    memory: ''

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5

configMap:
  enabled: false
  name: ''
  namespace: ''
  data: { }

secrets:
  name: ''
  namespace: ''
  enabled: false
  data: { }

certificate:
  enabled: false
  name: ''
  namespace: ''
  secretName: ''
  issuerRef: ''
  commonName: ''
  dnsNames: { }

gateway:
  enabled: false
  name: ''
  namespace: ''
  specSelector: ''
  servers:
    - port:
        number: 80
        name: http
        protocol: http
      hosts:
        - '*'
    - port:
        number: 443
        name: https
        protocol: https
      hosts:
        - '*'
      tls:
        mode: SIMPLE
        credentialName: ''

virtualService:
  enabled: true
  name: ''
  namespace: prod
  host: "api.1flow.org"
  httpRoutes: { }
  tcpRoutes: { }

destinationRule:
  trafficPolicy: { }
  portLevelSettings: { }
  subsets: { }
  enabled: false
  name: ''
  host: ''
  namespace: ''
  gateway: ''
  routeDefinitions: { }
  destinationHost: ''
  destinationPort: ''
  healthCheckPath: ''
  allowOrigins:
    exact: "*"
  allowHeaders: { }
  allowMethods: { }

persistentVolume:
  enabled: false
  name: ''
  namespace: ''
  labelType: ''
  storage:
    className: ''
    capacity: ''
  accessModes: { }
  hostPath: ''

persistentVolumeClaim:
  name: ''
  namespace: ''
  enabled: false
  accessModes: { }
  storage: ''

cronJob:
  enabled: false
  name: ''
  namespace: ''
  schedule: "59 23 28-31 * *"
  restartPolicy: OnFailure
  containers:
    - name: hello
      image: busybox:1.28
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - date; echo Hello from the Kubernetes cluster


argocd:
  name: ''
  enabled: false
  namespace: ''
  projectName: ''
  sources: { }
  sync:
    automated:
      prune: 'false'
      selfHeal: 'false'
    options: { }
    retry:
      limit: ''
      backoffDuration: ''
      backOffMaxDuration: ''
      backOffFactor: ''
  destination:
    name: ''
    namespace: ''
    server: ''
  repository:
    url: ''
    path: ''
    targetRevision: '0.1.13'
    chart: 'flow-helm-chart'
    valueFiles: { }
  values: ''