{{- $name := coalesce .Values.certificate.name .Values.serviceProperties.name -}}
{{- $namespace := coalesce .Values.certificate.namespace .Values.serviceProperties.namespace -}}
{{- $enabled := .Values.certificate.enabled -}}

{{- if $enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: {{ default "letsencrypt" .Values.certificate.issuerRef.name }}
    kind: {{ default "ClusterIssuer" .Values.certificate.issuerRef.kind }}
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . }}
    {{- end }}
{{- end -}}