{{- $name := coalesce .Values.deployment.name .Values.serviceProperties.name -}}
{{- $namespace := coalesce .Values.deployment.namespace .Values.serviceProperties.namespace -}}
{{- $enabled := .Values.deployment.enabled -}}

{{ if $enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      name: {{ $name }}
      labels:
        app: {{ $name }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: {{ .Values.metrics.scrape | quote }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/path: {{ .Values.metrics.path | quote }}
      {{- end }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | toString }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{ if .Values.deployment.args }}
          args:
            {{- range .Values.deployment.args }}
            - {{ . | quote }}
            {{- end }}
          {{ end }}
          {{- if .Values.deployment.ports }}
          ports:
            {{- range .Values.deployment.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.deployment.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.deployment.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.startupProbe }}
          startupProbe:
{{ toYaml .Values.deployment.startupProbe | nindent 12 }}
          {{- end }}

          {{- if or .Values.resources.enabled .Values.resources.requests .Values.resources.limits }}
          resources:
            {{- if .Values.resources.limits }}
            limits:
              {{- if .Values.resources.limits.cpu }}
              cpu: {{ .Values.resources.limits.cpu }}
              {{- end }}
              {{- if .Values.resources.limits.memory }}
              memory: {{ .Values.resources.limits.memory }}
              {{- end }}
            {{- end }}
            {{- if .Values.resources.requests }}
            requests:
              {{- if .Values.resources.requests.cpu }}
              cpu: {{ .Values.resources.requests.cpu }}
              {{- end }}
              {{- if .Values.resources.requests.memory }}
              memory: {{ .Values.resources.requests.memory }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{ if or (.Values.configMap.enabled) (.Values.secrets.enabled) }}
          envFrom:
          {{ if .Values.configMap.enabled}}
            - configMapRef:
                name: {{ coalesce .Values.configMap.name .Values.serviceProperties.name }}
            {{ if .Values.secrets.enabled }}
            - secretRef:
                name: {{ coalesce .Values.secrets.name .Values.serviceProperties.name }}
            {{- end }}
          {{- end }}
          {{- end }}
      restartPolicy: {{ .Values.deployment.restartPolicy}}
{{ end }}