{{- $name := coalesce .Values.deployment.name .Values.serviceProperties.name -}}
{{- $namespace := coalesce .Values.deployment.namespace .Values.serviceProperties.namespace -}}
{{- $enabled := .Values.deployment.enabled -}}

{{ if $enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      name: {{ $name }}
      labels:
        app: {{ $name }}
      {{- if or .Values.metrics.enabled .Values.configMap.enabled .Values.secrets.enabled }}
      annotations:
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: {{ .Values.metrics.scrape | quote }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/path: {{ .Values.metrics.path | quote }}
        {{- end }}
        {{- if .Values.configMap.enabled }}
        checksum/config: {{ toYaml .Values.configMap.data | sha256sum }}
        {{- end }}
        {{- if .Values.secrets.enabled }}
        checksum/secret: {{ toYaml .Values.secrets.data | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.deployment.initContainers }}
      initContainers:
        {{- toYaml .Values.deployment.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: "{{ .Values.deployment.image.repository }}:{{ coalesce .Values.deployment.image.tag .Chart.AppVersion | toString }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{ if .Values.deployment.args }}
          args:
            {{- range .Values.deployment.args }}
            - {{ . | quote }}
            {{- end }}
          {{ end }}
          {{- if .Values.deployment.ports }}
          ports:
            {{- range .Values.deployment.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.deployment.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.deployment.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.startupProbe }}
          startupProbe:
{{ toYaml .Values.deployment.startupProbe | nindent 12 }}
          {{- end }}

          {{- if .Values.resources }}
          resources:
            {{- toYaml (omit .Values.resources "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.env }}
          env:
            {{- toYaml .Values.deployment.env | nindent 12 }}
          {{- end }}
          {{- if or .Values.configMap.enabled .Values.secrets.enabled }}
          envFrom:
            {{- if .Values.configMap.enabled }}
            - configMapRef:
                name: {{ coalesce .Values.configMap.name .Values.serviceProperties.name }}
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ coalesce .Values.secrets.name .Values.serviceProperties.name }}
            {{- end }}
          {{- end }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
{{ end }}