{{- $name := coalesce .Values.deployment.name .Values.serviceProperties.name -}}
{{- $namespace := coalesce .Values.deployment.namespace .Values.serviceProperties.namespace -}}
{{- $enabled := coalesce .Values.hpa.enabled .Values.autoscaling.enabled false -}}

{{ if $enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ coalesce .Values.hpa.minReplicas .Values.autoscaling.minReplicas }}
  maxReplicas: {{ coalesce .Values.hpa.maxReplicas .Values.autoscaling.maxReplicas }}
  metrics:
{{- if .Values.hpa.metrics }}
{{ toYaml .Values.hpa.metrics | indent 4 }}
{{- else }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
{{- end }}
{{- if .Values.hpa.behavior }}
  behavior:
{{ toYaml .Values.hpa.behavior | indent 4 }}
{{- end }}
{{- end }}