{{- $name := coalesce .Values.deployment.name .Values.serviceProperties.name -}}
{{- $namespace := coalesce .Values.deployment.namespace .Values.serviceProperties.namespace -}}
{{- $enabled := .Values.autoscaling.enabled -}}

{{ if $enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: pod_network_io_bytes_per_second
        target:
          type: AverageValue
          averageValue: 100M
{{- end }}