{{- $name := coalesce .Values.persistentVolumeClaim.name .Values.serviceProperties.name -}}
{{- $namespace := coalesce .Values.persistentVolumeClaim.namespace .Values.serviceProperties.namespace -}}
{{- $enabled := coalesce .Values.persistentVolumeClaim.enabled .Values.serviceProperties.enabled -}}

{{ if $enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  accessModes:
    {{- range .Values.persistentVolumeClaim.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
{{ end }}