{{- $name := coalesce .Values.secrets.name .Values.serviceProperties.name -}}
{{- $namespace := coalesce .Values.secrets.namespace .Values.serviceProperties.namespace -}}
{{- $enabled := .Values.secrets.enabled -}}

{{ if $enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
data:
    {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
    {{- end }}
{{- end }}