{{ if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.virtualService.namespace }}
spec:
  hosts:
    - {{ .Values.virtualService.host }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - name: {{ .Values.virtualService.name }}
      match:
        - uri:
            prefix: {{ .Values.virtualService.routePrefix }}
      route:
        - destination:
            host: {{ .Values.virtualService.destinationHost }}
            port:
              number: {{ .Values.virtualService.destinationPort }}
      corsPolicy:
        allowOrigins:
          {{- range $k, $v := .Values.virtualService.allowOrigins }}
          - {{ $k }}: {{ $v | quote }}
              {{- end }}
        allowHeaders:
          {{ range .Values.virtualService.allowHeaders }}
          - {{ . | quote }}
          {{- end }}
        allowMethods:
          {{ range .Values.virtualService.allowMethods }}
          - {{ . | quote }}
          {{- end }}
{{- end }}