{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers: |-
    {{- range .Values.gateway.servers }}
    - port: {{ .port.name }}
        number: {{ .port.number }}
        protocol: {{ .port.protocol | upper }}
      hosts: |-
      {{ range .hosts }}
        {{ . | quote }}
      {{- end }}
    {{- end }}
{{- end -}}