apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
spec:
  hosts:
    - {{ .Values.virtualService.host }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - name: {{ .Values.virtualService.name }}
      match:
        - uri:
            prefix: {{ .Values.virtualService.routePrefix }}
      route:
        - destination:
            host: {{ .Values.virtualService.destinationHost }}
            port:
              number: {{ .Values.virtualService.destinationPort }}
      corsPolicy:
        allowOrigins:
          - exact: "*"
        allowHeaders:
          - Content-Type
          - Authorization
        allowMethods:
          - GET
          - POST
          - PUT
          - PATCH